//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KipparitRy2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Postitoimipaikat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postitoimipaikat()
        {
            this.Asiakkaat = new HashSet<Asiakkaat>();
        }
    
        public int PostiID { get; set; }
        //[StringLength(5, MinimumLength = 5, ErrorMessage = "Kentt‰ [Postinumero] tarvitsee 5 numeroa")]
        //[RegularExpression(@"^([0-9])+$", ErrorMessage = "Postinumero saa sis‰lt‰‰ vain numeroita!")]
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakkaat> Asiakkaat { get; set; }
    }
}
