//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KipparitRy2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rekisteroitymiset
    {
        public int RekisterointiID { get; set; }
        public int TilaisuusID { get; set; }
        public int AsiakasID { get; set; }
    
        public virtual Asiakkaat Asiakkaat { get; set; }
        public virtual Tilaisuudet Tilaisuudet { get; set; }
    }
}
